baseURL: https://amanprakash59.tech

languageCode: en-us
title: "AmAn PraKasH"
theme: "toha"

# Manage languages
languages:
  en:
    languageName: English
    weight: 1
 

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON



# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will default to the theme logos if not provided.
  logo:
    main: /images/site/main-logo.svg
    inverted: /images/site/inverted-logo.svg
    favicon: /images/site/favicon.svg

  # GitHub repo of your site
  gitRepo: https://github.com/amanprakash59/website-aman
  # Default branch of your Git repo
  gitBranch: source

  # specify whether you want to write some blog posts or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: true

  # Configure Notes property
  notes:
    # Set a background color of note card header. Use any CSS color code/name.
    headerBackground: aliceblue
    # Set note card title color.
    headerTextColor: #1c2d41
